[package]
distribution = "2201.12.0"
org = "ballerinax"
name = "temenosManageAccountArrangementsAlerts"
version = "0.1.0"
license = ["Apache-2.0"]
authors = ["iamSahdoon"]
keywords = ["banking", "temenos", "api", "manage account arrangements alerts"]
repository = "https://github.com/iamSahdoon/module-ballerinax-temenosManageAccountArrangementsAlerts"

[build-options]
observabilityIncluded = true

[platform.java21]
graalvmCompatible = true
